---
galaxy_info:
  author: arthur orlov
  description: Install lxc, create base containers, clones them to make working copies
  company: ati.su
  license: MIT
  min_ansible_version: 1.9
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your 
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  - clustering
  #- database
  #- database:nosql
  #- database:sql
  - development
  #- monitoring
  #- networking
  #- packaging
  - system
  #- web
dependencies: []
